apiVersion: v1
kind: Service
metadata:
  name: logstash-service
  namespace: message-app
spec:
  selector:
    app: logstash
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: message-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: logstash:8.19.2
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/logstash/pipeline/
      volumes:
        - name: config-volume
          configMap:
            name: logstash-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: message-app
data:
  logstash.conf: |
    input {
      tcp {
        port => 5000
        codec => json_lines
      }
    }
    filter {
      # Ensure `data_stream.dataset` is present in logs
      if ![data_stream][dataset] {
      mutate {
        add_field => { "[data_stream][dataset]" => "unknown-app" }
        }
      }

    if ![data_stream][type] {
      mutate {
        add_field => { "[data_stream][type]" => "logs" }
        }
      }

    if ![data_stream][namespace] {
      mutate {
        add_field => { "[data_stream][namespace]" => "default" }
        }
      }
    }
  
    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        data_stream => true
        data_stream_type => "logs"
        data_stream_dataset => "%{[data_stream][dataset]}"
        data_stream_namespace => "%{[data_stream][namespace]}"
      }
    stdout { codec => rubydebug }
    # You can add elasticsearch or other outputs here later
    }
